export const ORDER_LIST_ROOT_STATE = Object.freeze({
  LOADING: 'loading',
  LIST: 'list',
  EMPTY: 'empty',
  ERROR: 'error',
})

export const ORDER_LIST_PATH = '/bev/Bgq3E/y7FiRay'

export const ORDER_STATUS = Object.freeze({
  CREATE: 10,
  EXAMINE_WAIT: 20,
  AUTO_REPEAT_EXAMINE_WAIT: 21,
  EXAMINE_PASS: 30,
  EXAMINE_FAIL: 40,
  WAIT_PAY: 70,
  WAY: 80,
  DUE: 90,
  COMPLETE: 100,
  DUE_COMPLETE: 101,
  ABANDONED: 110,
})

export const ORDER_LIST_FILTER = Object.freeze({
  PENDING_PAYMENT: 'pendingPayment',
  REVIEWING: 'reviewing',
  HISTORY: 'history',
})

export const ORDER_LIST_FILTERS = Object.freeze([
  ORDER_LIST_FILTER.PENDING_PAYMENT,
  ORDER_LIST_FILTER.REVIEWING,
  ORDER_LIST_FILTER.HISTORY,
])

export const ORDER_LIST_DEFAULT_FILTER = ORDER_LIST_FILTER.PENDING_PAYMENT

export const ORDER_LIST_FILTER_STATUSES = Object.freeze({
  [ORDER_LIST_FILTER.PENDING_PAYMENT]: Object.freeze([
    ORDER_STATUS.WAY,
    ORDER_STATUS.DUE,
  ]),
  [ORDER_LIST_FILTER.REVIEWING]: Object.freeze([
    ORDER_STATUS.CREATE,
    ORDER_STATUS.EXAMINE_WAIT,
    ORDER_STATUS.AUTO_REPEAT_EXAMINE_WAIT,
    ORDER_STATUS.EXAMINE_PASS,
    ORDER_STATUS.EXAMINE_FAIL,
    ORDER_STATUS.WAIT_PAY,
    ORDER_STATUS.ABANDONED,
  ]),
  [ORDER_LIST_FILTER.HISTORY]: Object.freeze([
    ORDER_STATUS.COMPLETE,
    ORDER_STATUS.DUE_COMPLETE,
  ]),
})

export const ORDER_LIST_STATUS_FILTER = Object.freeze({
  [ORDER_STATUS.CREATE]: ORDER_LIST_FILTER.REVIEWING,
  [ORDER_STATUS.EXAMINE_WAIT]: ORDER_LIST_FILTER.REVIEWING,
  [ORDER_STATUS.AUTO_REPEAT_EXAMINE_WAIT]: ORDER_LIST_FILTER.REVIEWING,
  [ORDER_STATUS.EXAMINE_PASS]: ORDER_LIST_FILTER.REVIEWING,
  [ORDER_STATUS.EXAMINE_FAIL]: ORDER_LIST_FILTER.REVIEWING,
  [ORDER_STATUS.WAIT_PAY]: ORDER_LIST_FILTER.REVIEWING,
  [ORDER_STATUS.WAY]: ORDER_LIST_FILTER.PENDING_PAYMENT,
  [ORDER_STATUS.DUE]: ORDER_LIST_FILTER.PENDING_PAYMENT,
  [ORDER_STATUS.COMPLETE]: ORDER_LIST_FILTER.HISTORY,
  [ORDER_STATUS.DUE_COMPLETE]: ORDER_LIST_FILTER.HISTORY,
  [ORDER_STATUS.ABANDONED]: ORDER_LIST_FILTER.REVIEWING,
})

export const ORDER_LIST_STATUS_MESSAGE_ID = Object.freeze({
  [ORDER_STATUS.CREATE]: '50',
  [ORDER_STATUS.EXAMINE_WAIT]: '51',
  [ORDER_STATUS.AUTO_REPEAT_EXAMINE_WAIT]: '51',
  [ORDER_STATUS.EXAMINE_PASS]: '52',
  [ORDER_STATUS.EXAMINE_FAIL]: '53',
  [ORDER_STATUS.WAIT_PAY]: '54',
  [ORDER_STATUS.WAY]: '55',
  [ORDER_STATUS.DUE]: '56',
  [ORDER_STATUS.COMPLETE]: '57',
  [ORDER_STATUS.DUE_COMPLETE]: '57',
  [ORDER_STATUS.ABANDONED]: '58',
})

export const ORDER_LIST_CARD_MODE = Object.freeze({
  APPLICATION: 'application',
  REPAYMENT: 'repayment',
  COMPLETED: 'completed',
})

export const ORDER_LIST_STATUS_MODE = Object.freeze({
  [ORDER_STATUS.CREATE]: ORDER_LIST_CARD_MODE.APPLICATION,
  [ORDER_STATUS.EXAMINE_WAIT]: ORDER_LIST_CARD_MODE.APPLICATION,
  [ORDER_STATUS.AUTO_REPEAT_EXAMINE_WAIT]: ORDER_LIST_CARD_MODE.APPLICATION,
  [ORDER_STATUS.EXAMINE_PASS]: ORDER_LIST_CARD_MODE.APPLICATION,
  [ORDER_STATUS.EXAMINE_FAIL]: ORDER_LIST_CARD_MODE.APPLICATION,
  [ORDER_STATUS.WAIT_PAY]: ORDER_LIST_CARD_MODE.APPLICATION,
  [ORDER_STATUS.WAY]: ORDER_LIST_CARD_MODE.REPAYMENT,
  [ORDER_STATUS.DUE]: ORDER_LIST_CARD_MODE.REPAYMENT,
  [ORDER_STATUS.COMPLETE]: ORDER_LIST_CARD_MODE.COMPLETED,
  [ORDER_STATUS.DUE_COMPLETE]: ORDER_LIST_CARD_MODE.COMPLETED,
  [ORDER_STATUS.ABANDONED]: ORDER_LIST_CARD_MODE.APPLICATION,
})

export const ORDER_LIST_CARD_VARIANT = Object.freeze({
  DEFAULT: 'default',
  OVERDUE: 'overdue',
})

export const ORDER_LIST_STATUS_VARIANT = Object.freeze({
  [ORDER_STATUS.DUE]: ORDER_LIST_CARD_VARIANT.OVERDUE,
})

export const ORDER_LIST_STATUS_BADGE_COLOR = Object.freeze({
  [ORDER_STATUS.CREATE]: '#ffbc41',
  [ORDER_STATUS.EXAMINE_WAIT]: '#f125a8',
  [ORDER_STATUS.AUTO_REPEAT_EXAMINE_WAIT]: '#f125a8',
  [ORDER_STATUS.EXAMINE_PASS]: '#04ca1c',
  [ORDER_STATUS.EXAMINE_FAIL]: '#f64705',
  [ORDER_STATUS.WAIT_PAY]: '#155dfc',
  [ORDER_STATUS.WAY]: '#ff7c00',
  [ORDER_STATUS.DUE]: '#f64705',
  [ORDER_STATUS.COMPLETE]: '#04ca1c',
  [ORDER_STATUS.DUE_COMPLETE]: '#04ca1c',
  [ORDER_STATUS.ABANDONED]: '#f64705',
})

export const ORDER_LIST_SUPPORTED_STATUSES = Object.freeze(Object.values(ORDER_STATUS))

export function getOrderListFilterForStatus(orderStatus) {
  return ORDER_LIST_STATUS_FILTER[orderStatus] ?? null
}

export function getOrderListCardMode(orderStatus) {
  return ORDER_LIST_STATUS_MODE[orderStatus] ?? null
}

export function getOrderListCardVariant(orderStatus) {
  return ORDER_LIST_STATUS_VARIANT[orderStatus] ?? ORDER_LIST_CARD_VARIANT.DEFAULT
}

export function getOrderListBadgeColor(orderStatus) {
  return ORDER_LIST_STATUS_BADGE_COLOR[orderStatus] ?? ''
}
